export const FEED_POSTS_REQUEST="FEED_POSTS_REQUEST"
export const FEED_POSTS_SUCCESS="FEED_POSTS_SUCCESS"
export const FEED_POSTS_FAILED="FEED_POSTS_FAILED"

export const FEED_REELS_REQUEST="FEED_REELS_REQUEST"
export const FEED_REELS_SUCCESS="FEED_REELS_SUCCESS"
export const FEED_REELS_FAILED="FEED_REELS_FAILED"

export const FEED_STORIES_REQUEST="FEED_STORIES_REQUEST"
export const FEED_STORIES_SUCCESS="FEED_STORIES_SUCCESS"
export const FEED_STORIES_FAILED="FEED_STORIES_FAILED"

export const FEED_REQUESTS_REQUEST="FEED_REQUESTS_REQUEST"
export const FEED_REQUESTS_SUCCESS="FEED_REQUESTS_SUCCESS"
export const FEED_REQUESTS_FAILED="FEED_REQUESTS_FAILED"

export const FEED_ACTIVITY_REQUEST="FEED_ACTIVITY_REQUEST"
export const FEED_ACTIVITY_SUCCESS="FEED_ACTIVITY_SUCCESS"
export const FEED_ACTIVITY_FAILED="FEED_ACTIVITY_FAILED"