export const LIKE_A_POST_REQUEST="LIKE_A_POST_REQUEST"
export const LIKE_A_POST_SUCCESS="LIKE_A_POST_SUCCESS"
export const LIKE_A_POST_FAILED="LIKE_A_POST_FAILED"

export const COMMENT_POST_REQUEST="COMMENT_POST_REQUEST"
export const COMMENT_POST_SUCCESS="COMMENT_POST_SUCCESS"
export const COMMENT_POST_FAILED="COMMENT_POST_FAILED"

export const CREATE_POST_REQUEST="CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS="CREATE_POST_SUCCESS"
export const CREATE_POST_FAILED="CREATE_POST_FAILED"

