export const LIKE_A_REEL_REQUEST="LIKE_A_REEL_REQUEST"
export const LIKE_A_REEL_SUCCESS="LIKE_A_REEL_SUCCESS"
export const LIKE_A_REEL_FAILED="LIKE_A_REEL_FAILED"

export const COMMENT_REEL_REQUEST="COMMENT_REEL_REQUEST"
export const COMMENT_REEL_SUCCESS="COMMENT_REEL_SUCCESS"
export const COMMENT_REEL_FAILED="COMMENT_REEL_FAILED"

export const CREATE_REEL_REQUEST="CREATE_REEL_REQUEST"
export const CREATE_REEL_SUCCESS="CREATE_REEL_SUCCESS"
export const CREATE_REEL_FAILED="CREATE_REEL_FAILED"

