export const ACCEPT_REQUEST_REQUEST="ACCEPT_REQUEST_REQUEST"
export const ACCEPT_REQUEST_SUCCESS="ACCEPT_REQUEST_SUCCESS"
export const ACCEPT_REQUEST_FAILED="ACCEPT_REQUEST_FAILED"

export const DELETE_REQUEST_REQUEST="DELETE_REQUEST_REQUEST"
export const DELETE_REQUEST_SUCCESS="DELETE_REQUEST_SUCCESS"
export const DELETE_REQUEST_FAILED="DELETE_REQUEST_FAILED"

export const DELETE_ACTIVITY_REQUEST="DELETE_ACTIVITY_REQUEST"
export const DELETE_ACTIVITY_SUCCESS="DELETE_ACTIVITY_SUCCESS"
export const DELETE_ACTIVITY_FAILED="DELETE_ACTIVITY_FAILED"

