export const CREATE_STORY_REQUEST="CREATE_STORY_REQUEST"
export const CREATE_STORY_SUCCESS="CREATE_STORY_SUCCESS"
export const CREATE_STORY_FAILED="CREATE_STORY_FAILED"

export const GET_OWN_STORY_REQUEST="GET_OWN_STORY_REQUEST"
export const GET_OWN_STORY_SUCCESS="GET_OWN_STORY_SUCCESS"
export const GET_OWN_STORY_FAILED="GET_OWN_STORY_FAILED"